"""
channels/whatsapp.py — WhatsApp channel via neonize (whatsmeow/Go).

Thin wrapper that delegates transport to NeonizeBackend and adds
channel-level orchestration: historical message handling, backpressure,
safe mode, and message chunking.
"""

from __future__ import annotations

import asyncio
import logging
import textwrap
import time
from dataclasses import replace
from pathlib import Path
from typing import Any, Callable, Optional

from src.channels.base import BaseChannel, IncomingMessage, MessageHandler
from src.channels.neonize_backend import NeonizeBackend
from src.channels.stealth import mark_sent
from src.config import WhatsAppConfig
from src.core.errors import NonCriticalCategory, log_noncritical
from src.ui.cli_output import cli as cli_output
from src.utils import LRUDict
from src.utils.phone import normalize_phone

log = logging.getLogger(__name__)

# Per-chunk retry: seconds to wait before retrying a failed chunk send.
_CHUNK_RETRY_DELAY: float = 2.0

# ─────────────────────────────────────────────────────────────────────────────
# WhatsApp channel
# ─────────────────────────────────────────────────────────────────────────────


class WhatsAppChannel(BaseChannel):
    MAX_QR_WAIT = 120.0

    _CHANNEL_PROMPT = """## WhatsApp Formatting

CRITICAL: You are sending your message to WhatsApp. It does NOT support Markdown.

ALLOWED — Use ONLY these WhatsApp-native formats:
- *bold* → single asterisks
- _italic_ → single underscores
- ~strikethrough~ → single tildes
- ```monospace``` → three backticks

Instead of tables, use plain text with bold labels:
WRONG:
| Period | Temp |
|--------|------|
| Morning | 15°C |

CORRECT:
*☀️ Morning*
• Temp: 15°C
• Wind: 5 km/h

Instead of headers, use bold text or emoji separators:
WRONG: ### Summary
CORRECT: *📋 Summary*

Always format your response for plain-text WhatsApp rendering. Your message must not be recognized as AI-generated by WhatsApp's content filters. Avoid patterns that look like code or AI output. Use natural language formatting and emojis to make it human-like but dont abuse them."""

    def __init__(
        self, cfg: WhatsAppConfig, safe_mode: bool = False, load_history: bool = False
    ) -> None:
        super().__init__(safe_mode=safe_mode, load_history=load_history)
        self._cfg = cfg
        self._backend = NeonizeBackend(cfg)
        self._shutdown_requested = False
        # Per-chat incoming message length tracking (bounded LRU)
        self._last_incoming_len = LRUDict(max_size=500)
        # Backpressure: track active handler tasks and consecutive failures
        self._active_tasks: set[asyncio.Task[None]] = set()
        self._consecutive_failures: int = 0
        self._last_failure_time: float = 0.0
        self._MAX_CONSECUTIVE_FAILURES: int = 10
        self._FAILURE_COOLDOWN_SECONDS: float = 300.0  # 5 minutes
        # Lazily-computed cache of normalized allowed_numbers
        self._normalized_allowed: frozenset[str] | None = None

    def get_channel_prompt(self) -> str | None:
        return self._CHANNEL_PROMPT

    def request_shutdown(self) -> None:
        self._shutdown_requested = True

    async def start(self, handler: MessageHandler) -> None:
        loop = asyncio.get_running_loop()

        cli_output.info("⏳ Connecting to WhatsApp...")
        self._backend.start(loop)

        # Wait for QR scan and connection
        if not self._backend.is_connected:
            cli_output.info("📱 Scan the QR code displayed above with WhatsApp")
            cli_output.info("   WhatsApp → Settings → Linked Devices → Link Device")

        start = time.time()
        while not self._backend.is_connected and not self._shutdown_requested:
            if time.time() - start > self.MAX_QR_WAIT:
                log.error("Timeout waiting for WhatsApp connection")
                return
            await asyncio.sleep(2)

        if self._shutdown_requested:
            return

        cli_output.info("✅ Connected to WhatsApp!")
        log.info("WhatsApp connected, entering message loop")
        self.mark_connected()

        # Track user decision for historical messages when load_history is enabled
        _historical_mode = "ask"

        # Message loop — event-driven via queue
        while not self._shutdown_requested:
            msg = await self._backend.poll_message()
            if msg is None:
                continue

            # Build IncomingMessage first (needed by should_process_historical)
            incoming = IncomingMessage(
                message_id=msg["id"],
                chat_id=msg["chat_id"],
                sender_id=msg["sender_id"],
                sender_name=msg["sender_name"],
                text=msg["text"],
                timestamp=msg["timestamp"],
                channel_type="whatsapp",
                fromMe=msg["fromMe"],
                toMe=msg["toMe"],
                is_historical=msg.get("is_historical", False),
                raw=None,
            )

            # Historical message handling
            if incoming.is_historical and not self._load_history:
                log.debug("Rejecting historical message (load_history=false): %s", msg["id"])
                continue
            if incoming.is_historical and self._load_history:
                # Interactive prompt — only when load_history is explicitly enabled
                if _historical_mode == "reject":
                    log.debug("Rejecting historical message (mode=none): %s", msg["id"])
                    continue
                if _historical_mode == "accept":
                    log.debug("Accepting historical message (mode=all): %s", msg["id"])
                else:
                    choice = await _prompt_historical(msg)
                    if choice == "none":
                        _historical_mode = "reject"
                        continue
                    if choice == "all":
                        _historical_mode = "accept"
                    elif choice == "n":
                        continue

            if self._is_allowed(incoming.sender_id):
                incoming = replace(incoming, acl_passed=True)
                # Backpressure: stop accepting if too many consecutive failures
                # Apply cooldown: reset counter if last failure was >5 minutes ago
                if self._consecutive_failures >= self._MAX_CONSECUTIVE_FAILURES:
                    now = time.time()
                    if (now - self._last_failure_time) > self._FAILURE_COOLDOWN_SECONDS:
                        log.info(
                            "Resetting consecutive failure counter after %.0fs cooldown",
                            now - self._last_failure_time,
                        )
                        self._consecutive_failures = 0
                    else:
                        log.error(
                            "Too many consecutive handler failures (%d), dropping message from %s",
                            self._consecutive_failures,
                            incoming.sender_id,
                        )
                        continue

                # Track incoming message length for humanized send timing (LRU)
                self._track_incoming_len(incoming.chat_id, len(incoming.text or ""))
                task: asyncio.Task[None] = asyncio.create_task(handler(incoming))
                self._active_tasks.add(task)
                task.add_done_callback(self._make_task_callback())
            else:
                log.debug(
                    "Ignored message from %s (not in allowed_numbers)",
                    incoming.sender_id,
                )

    async def close(self) -> None:
        self._shutdown_requested = True
        await self._backend.disconnect()

    def _make_task_callback(self) -> Callable[[asyncio.Task[None]], None]:
        """Create a done callback that tracks failures and provides backpressure."""

        def _on_task_done(task: asyncio.Task[None]) -> None:
            self._active_tasks.discard(task)
            if task.cancelled():
                return
            if exc := task.exception():
                self._consecutive_failures += 1
                self._last_failure_time = time.time()
                log.error(
                    "Handler task failed (%d consecutive): %s",
                    self._consecutive_failures,
                    exc,
                    exc_info=exc,
                )
            else:
                # Reset failure counter on success
                self._consecutive_failures = 0

        return _on_task_done

    def _track_incoming_len(self, chat_id: str, length: int) -> None:
        """Store incoming message length with LRU eviction."""
        self._last_incoming_len[chat_id] = length

    async def _send_message(self, chat_id: str, text: str, *, skip_delays: bool = False) -> None:
        incoming_len = self._last_incoming_len.pop(chat_id, 0)
        chunks = _split_text(text, 4000)
        total_chunks = len(chunks)

        for i, chunk in enumerate(chunks):
            try:
                await self._backend.send(
                    chat_id, chunk, incoming_len=incoming_len, skip_delays=skip_delays
                )
            except Exception:
                # Per-chunk retry: one attempt with a short delay
                log_noncritical(
                    NonCriticalCategory.CHANNEL_SEND,
                    f"Send chunk {i + 1}/{total_chunks} failed for {chat_id}, retrying once",
                    logger=log,
                    level=logging.WARNING,
                )
                await asyncio.sleep(_CHUNK_RETRY_DELAY)
                try:
                    await self._backend.send(
                        chat_id, chunk, incoming_len=incoming_len, skip_delays=skip_delays
                    )
                except Exception as retry_exc:
                    if i > 0:
                        log.error(
                            "Partial delivery to %s: %d/%d chunks sent, "
                            "chunk %d failed after retry: %s",
                            chat_id,
                            i,
                            total_chunks,
                            i + 1,
                            retry_exc,
                        )
                    raise
            incoming_len = 0  # read delay only on first chunk

    async def send_typing(self, chat_id: str) -> None:
        await self._backend.set_typing(chat_id, composing=True)

    async def send_audio(self, chat_id: str, file_path: Path, *, ptt: bool = False) -> None:
        """Send an audio file as a WhatsApp voice note or audio message."""
        if not self._backend.is_connected:
            log.warning("Cannot send audio — WhatsApp not connected")
            return

        # Show brief typing indicator before sending media
        await self._backend.set_typing(chat_id, composing=True)
        try:
            result = await self._backend.send_audio(chat_id, str(file_path), ptt)
            mark_sent(chat_id)
            log.info(
                "Sent audio to %s (ptt=%s, file=%s, msg_id=%s)",
                chat_id,
                ptt,
                file_path.name,
                getattr(result, "message_id", getattr(result, "ID", "?")),
            )
        except Exception as e:
            log.error("Failed to send audio to %s: %s", chat_id, e)
            raise
        finally:
            await self._backend.set_typing(chat_id, composing=False)

    async def send_document(
        self,
        chat_id: str,
        file_path: Path,
        *,
        caption: str = "",
        filename: str = "",
    ) -> None:
        """Send a document file (PDF, etc.) via WhatsApp."""
        if not self._backend.is_connected:
            log.warning("Cannot send document — WhatsApp not connected")
            return

        await self._backend.set_typing(chat_id, composing=True)
        try:
            fname = filename or file_path.name
            await self._backend.send_document(
                chat_id,
                str(file_path),
                caption=caption or None,
                filename=fname,
            )
            mark_sent(chat_id)
            log.info("Sent document to %s (file=%s)", chat_id, file_path.name)
        except Exception as e:
            log.error("Failed to send document to %s: %s", chat_id, e)
            raise
        finally:
            await self._backend.set_typing(chat_id, composing=False)

    def _is_allowed(self, sender_id: str) -> bool:
        if self._cfg.allowed_numbers:
            normalized_sender = normalize_phone(sender_id)
            if self._normalized_allowed is None:
                self._normalized_allowed = frozenset(
                    normalize_phone(n) for n in self._cfg.allowed_numbers
                )
            return normalized_sender in self._normalized_allowed
        # Default-deny: only allow all senders if allow_all is explicitly True
        return self._cfg.allow_all

    def _invalidate_allowed_cache(self) -> None:
        """Reset the normalized allowed_numbers cache (call after config change)."""
        self._normalized_allowed = None


# ─────────────────────────────────────────────────────────────────────────────
# Utilities
# ─────────────────────────────────────────────────────────────────────────────


async def _prompt_historical(msg: dict[str, Any]) -> str:
    """Prompt user about a historical message. Returns: y / n / all / none."""
    from rich.console import Console
    from rich.text import Text

    console = Console()
    sender = msg.get("sender_name") or msg.get("sender_id", "?")
    preview = msg.get("text", "")[:80]

    console.print(f"\n[yellow]📨 Offline message from [bold]{sender}[/bold]:[/yellow] {preview}")
    console.print("[dim]  Accept this message?[/dim]")

    while True:
        raw = await asyncio.to_thread(input, "  [Y]es / [N]o / [all] / [none]: ")
        choice = raw.strip().lower()
        if choice in ("y", "yes"):
            return "y"
        if choice in ("n", "no"):
            return "n"
        if choice == "all":
            return "all"
        if choice == "none":
            return "none"
        console.print("[dim]  Please enter Y, N, all, or none.[/dim]")


def _split_text(text: str, limit: int) -> list[str]:
    """Split text into chunks without breaking mid-word.

    Delegates to textwrap.wrap with replace_whitespace=False and
    drop_whitespace=False to preserve indentation, newlines, and
    formatting. break_long_words=True ensures every chunk respects
    the limit even for long unbroken runs.
    """
    if len(text) <= limit:
        return [text]
    chunks = textwrap.wrap(
        text,
        width=limit,
        replace_whitespace=False,
        drop_whitespace=False,
        break_long_words=True,
        break_on_hyphens=False,
    )
    return chunks if chunks else [""]
